/* Ngữ pháp: các thì + chủ đề + Part 5 từ vựng + Part 5 nâng cao.
   Câu hỏi: [đề, [đáp án], index đúng, giải thích, (tag)]  — đáp án được xáo khi hiển thị. */

const TENSE_REF = [
 {id:"ps",name:"Hiện tại đơn",en:"Present simple",
  f:["S + V(s/es)","S + do/does not + V","Do/Does + S + V?"],
  use:"Thói quen, sự thật, lịch trình cố định (tàu, xe, giờ mở cửa).",
  sig:"always, usually, often, every day/week, on Mondays, once a month",
  ex:"The shuttle bus <em>leaves</em> every 30 minutes."},
 {id:"pc",name:"Hiện tại tiếp diễn",en:"Present continuous",
  f:["S + am/is/are + V-ing","S + am/is/are not + V-ing","Am/Is/Are + S + V-ing?"],
  use:"Đang xảy ra lúc nói; việc tạm thời; kế hoạch tương lai gần đã sắp xếp.",
  sig:"now, right now, at the moment, currently, this week, Look!",
  ex:"We <em>are meeting</em> the client tomorrow (đã hẹn)."},
 {id:"pp",name:"Hiện tại hoàn thành",en:"Present perfect",
  f:["S + have/has + V3","S + have/has not + V3","Have/Has + S + V3?"],
  use:"Bắt đầu trong quá khứ, kéo dài đến nay; kết quả còn ở hiện tại; số lần đến nay.",
  sig:"since + mốc, for + khoảng, already, yet, just, recently, so far, over the past …, the first time",
  ex:"Ms. Lan <em>has worked</em> here since 2019."},
 {id:"ppc",name:"Hiện tại hoàn thành tiếp diễn",en:"Present perfect continuous",
  f:["S + have/has been + V-ing","S + have/has not been + V-ing","Have/Has + S + been + V-ing?"],
  use:"Nhấn mạnh quá trình liên tục đến hiện tại (và có thể còn tiếp).",
  sig:"for, since, all day, all morning, How long …?",
  ex:"The team <em>has been working</em> on it for six months."},
 {id:"pas",name:"Quá khứ đơn",en:"Past simple",
  f:["S + V2/ed","S + did not + V","Did + S + V?"],
  use:"Việc đã xảy ra và kết thúc tại thời điểm xác định trong quá khứ.",
  sig:"yesterday, last week/year, … ago, in 2020, when + quá khứ",
  ex:"The board <em>approved</em> the plan last Monday."},
 {id:"pac",name:"Quá khứ tiếp diễn",en:"Past continuous",
  f:["S + was/were + V-ing","S + was/were not + V-ing","Was/Were + S + V-ing?"],
  use:"Đang xảy ra tại một thời điểm trong quá khứ; việc đang diễn ra thì bị việc khác xen vào.",
  sig:"while, at 3 P.M. yesterday, when (việc xen vào chia QKĐ)",
  ex:"The power went out while we <em>were giving</em> the presentation."},
 {id:"pap",name:"Quá khứ hoàn thành",en:"Past perfect",
  f:["S + had + V3","S + had not + V3","Had + S + V3?"],
  use:"Xảy ra TRƯỚC một việc khác trong quá khứ; câu tường thuật lùi thì.",
  sig:"by the time + QKĐ, before, after, already (trong câu quá khứ)",
  ex:"By the time we arrived, the meeting <em>had started</em>."},
 {id:"fs",name:"Tương lai đơn",en:"Future simple",
  f:["S + will + V","S + will not (won't) + V","Will + S + V?"],
  use:"Quyết định ngay lúc nói, dự đoán, lời hứa, lời đề nghị.",
  sig:"tomorrow, next week, soon, in 2030, I think, probably",
  ex:"The new system <em>will be</em> installed next week."},
 {id:"bgt",name:"Be going to",en:"Be going to",
  f:["S + am/is/are going to + V","S + am/is/are not going to + V","Am/Is/Are + S + going to + V?"],
  use:"Dự định đã có từ trước; dự đoán có căn cứ ở hiện tại.",
  sig:"kế hoạch đã quyết; Look at the clouds!",
  ex:"Mr. Tuan <em>is going to give</em> a speech next Friday."},
 {id:"fc",name:"Tương lai tiếp diễn",en:"Future continuous",
  f:["S + will be + V-ing","S + will not be + V-ing","Will + S + be + V-ing?"],
  use:"Sẽ đang diễn ra tại một thời điểm trong tương lai.",
  sig:"at this time tomorrow, at 10 A.M. next Monday, throughout the weekend",
  ex:"At this time tomorrow, I <em>will be flying</em> to Da Nang."},
 {id:"fp",name:"Tương lai hoàn thành",en:"Future perfect",
  f:["S + will have + V3","S + will not have + V3","Will + S + have + V3?"],
  use:"Sẽ hoàn thành TRƯỚC một mốc trong tương lai.",
  sig:"by + mốc tương lai, by the time + HTĐ, by the end of next …",
  ex:"By the end of the year, we <em>will have opened</em> 20 stores."},
 {id:"pv",name:"Bị động theo thì",en:"Passive voice",
  f:["is/are + V3 · is being + V3 · has been + V3","was/were + V3 · was being + V3 · had been + V3","will be + V3 · will have been + V3 · modal + be + V3"],
  use:"Giữ nguyên thì, chỉ đổi động từ thành be (chia theo thì) + V3.",
  sig:"Chủ ngữ là vật / không có tân ngữ sau chỗ trống / có by + người",
  ex:"Three new employees <em>have been hired</em> since January."}
];
const TENSE_TIPS = [
 "Sau when, before, after, as soon as, once, until, if, unless (mệnh đề thời gian/điều kiện) → dùng HIỆN TẠI cho nghĩa tương lai, không dùng will.",
 "since + mốc thời gian / for + khoảng thời gian / so far / over the past … → hiện tại hoàn thành.",
 "by + mốc quá khứ, by the time + QKĐ → had V3 · by + mốc tương lai, by the time + HTĐ → will have V3.",
 "Thấy yesterday, last, ago, in + năm đã qua → loại ngay mọi đáp án hoàn thành.",
 "Tường thuật bằng said/told/announced (quá khứ) → động từ sau lùi một thì."
];
const TENSE_Q = [
 ["The shuttle bus to the airport ______ every thirty minutes.",["leaves","leave","is leaving","left"],0,"every thirty minutes → lịch trình cố định, chủ ngữ số ít.","ps"],
 ["Mr. Park usually ______ the weekly report on Fridays.",["submits","submit","submitted","has submitted"],0,"usually → hiện tại đơn, chủ ngữ số ít.","ps"],
 ["The museum ______ at 9 A.M. on weekdays.",["opens","open","opened","has opened"],0,"Giờ mở cửa cố định → hiện tại đơn.","ps"],
 ["Our store ______ not accept personal checks.",["does","do","is","has"],0,"Phủ định HTĐ, chủ ngữ số ít → does not.","ps"],
 ["How often ______ the technicians inspect the machines?",["do","does","are","have"],0,"Chủ ngữ số nhiều (technicians) + V nguyên mẫu → do.","ps"],
 ["Ms. Hoa can't take your call right now because she ______ with a client.",["is meeting","meets","met","has met"],0,"right now → hiện tại tiếp diễn.","pc"],
 ["The company is currently ______ applications for the sales position.",["accepting","accept","accepts","accepted"],0,"is currently + V-ing.","pc"],
 ["We ______ the new branch manager for lunch tomorrow; the table is already booked.",["are meeting","meet","met","have met"],0,"Kế hoạch đã sắp xếp (đặt bàn rồi) → hiện tại tiếp diễn.","pc"],
 ["Look! The workers ______ the sign in front of the building.",["are replacing","replace","replaced","have replaced"],0,"Look! → đang diễn ra.","pc"],
 ["This week, the cafeteria ______ a special vegetarian menu.",["is offering","offer","offered","has been offered"],0,"Việc tạm thời trong tuần này → hiện tại tiếp diễn.","pc"],
 ["Ms. Lan ______ in the marketing department since 2019.",["has worked","works","worked","will work"],0,"since + mốc → HTHT.","pp"],
 ["We ______ received your payment yet.",["haven't","didn't","don't","won't"],0,"yet ở câu phủ định → HTHT.","pp"],
 ["Sales of electric cars ______ steadily over the past three years.",["have risen","rise","rose","will rise"],0,"over the past + khoảng → HTHT.","pp"],
 ["The new manager has ______ made several changes to the schedule.",["already","yet","since","ago"],0,"have/has + already + V3.","pp"],
 ["So far, more than 200 people ______ for the workshop.",["have registered","register","registered","will register"],0,"So far → HTHT.","pp"],
 ["This is the first time the company ______ a trade fair abroad.",["has attended","attends","attended","will attend"],0,"This is the first time + HTHT.","pp"],
 ["The team ______ on the project for six months and expects to finish it soon.",["has been working","works","worked","had worked"],0,"for + khoảng, vẫn đang tiếp diễn → HTHT tiếp diễn.","ppc"],
 ["Customers ______ about the slow Internet connection all morning.",["have been complaining","complain","had complained","will complain"],0,"all morning, đến giờ vẫn tiếp → HTHT tiếp diễn.","ppc"],
 ["How long ______ you been waiting for the shipment?",["have","are","did","were"],0,"How long + have/has + been + V-ing.","ppc"],
 ["The board ______ the budget proposal at last Monday's meeting.",["approved","approves","has approved","had approved"],0,"last Monday → quá khứ đơn.","pas"],
 ["Mr. Nam ______ to Singapore three days ago.",["traveled","travels","has traveled","travel"],0,"ago → quá khứ đơn.","pas"],
 ["When the CEO ______ the factory in 2021, she praised the staff.",["visited","visits","has visited","had visited"],0,"in 2021 → quá khứ đơn.","pas"],
 ["The company ______ its first store in 2010.",["opened","opens","has opened","had been opened"],0,"in 2010 → quá khứ đơn, chủ động (có tân ngữ).","pas"],
 ["______ you receive the invoice I sent yesterday?",["Did","Do","Have","Had"],0,"yesterday → Did + S + V.","pas"],
 ["The power went out while we ______ the presentation.",["were giving","give","gave","have given"],0,"while + việc đang diễn ra thì bị xen ngang → QK tiếp diễn.","pac"],
 ["At 3 P.M. yesterday, Ms. Thu ______ with the suppliers.",["was meeting","meets","has met","will meet"],0,"Thời điểm cụ thể trong quá khứ → QK tiếp diễn.","pac"],
 ["I was reviewing the contract when the client ______.",["called","was calling","calls","has called"],0,"Việc xen vào (when) → quá khứ đơn.","pac"],
 ["While the technicians ______ the system, employees could not access e-mail.",["were updating","update","updated","have updated"],0,"while + QK tiếp diễn.","pac"],
 ["By the time the guests arrived, the caterers ______ the tables.",["had set","set","have set","will set"],0,"by the time + QKĐ → QKHT.","pap"],
 ["The meeting ______ when I got to the office.",["had already started","already started","has already started","already starts"],0,"Xảy ra trước việc 'got' (quá khứ) → QKHT.","pap"],
 ["Ms. Kim said that she ______ the report the day before.",["had finished","finishes","has finished","will finish"],0,"Tường thuật quá khứ + the day before → lùi thì QKHT.","pap"],
 ["After the manager ______ all the applications, she called three candidates.",["had reviewed","reviews","has reviewed","will review"],0,"Việc xong trước 'called' → QKHT.","pap"],
 ["The client had never ______ our products before the trade show.",["used","use","using","uses"],0,"had + V3.","pap"],
 ["The new software ______ installed next week.",["will be","is","was","has been"],0,"next week → tương lai, bị động will be V3.","fs"],
 ["“The phone is ringing.” — “I ______ answer it.”",["will","am","did","have"],0,"Quyết định ngay lúc nói → will.","fs"],
 ["We ______ you as soon as your order is ready.",["will contact","contact","contacted","have contacted"],0,"Mệnh đề chính mang nghĩa tương lai → will; vế as soon as dùng hiện tại.","fs"],
 ["According to the forecast, it ______ rain heavily tomorrow.",["is going to","was going to","has","had"],0,"Dự đoán có căn cứ → be going to.","bgt"],
 ["Mr. Tuan ______ give a speech at the opening ceremony next Friday.",["is going to","was","has","had been"],0,"Kế hoạch đã định → is going to + V.","bgt"],
 ["At this time tomorrow, I ______ to Da Nang for the conference.",["will be flying","fly","flew","have flown"],0,"At this time tomorrow → tương lai tiếp diễn.","fc"],
 ["Please don't call Mr. Long at 10 A.M.; he ______ a job interview then.",["will be conducting","conducts","conducted","has conducted"],0,"Sẽ đang diễn ra lúc 10 giờ → tương lai tiếp diễn.","fc"],
 ["Our technicians ______ maintenance work throughout the weekend.",["will be performing","performed","have performed","perform"],0,"Kéo dài suốt khoảng thời gian tương lai → tương lai tiếp diễn.","fc"],
 ["By the end of this year, the company ______ 20 new stores.",["will have opened","opens","opened","has opened"],0,"By the end of + tương lai → tương lai hoàn thành.","fp"],
 ["By the time you arrive, we ______ the preparations.",["will have finished","finish","had finished","finished"],0,"by the time + HTĐ → tương lai hoàn thành.","fp"],
 ["By 2030, Mr. Bao ______ for the firm for 25 years.",["will have worked","works","worked","has worked"],0,"By + mốc tương lai → tương lai hoàn thành.","fp"],
 ["Please wait in the lobby until Ms. Ngoc ______.",["arrives","will arrive","arrived","arriving"],0,"until → mệnh đề thời gian dùng hiện tại.","tc"],
 ["Once the renovation ______ complete, the library will reopen.",["is","will be","was","being"],0,"once → hiện tại cho nghĩa tương lai.","tc"],
 ["We will start the meeting after everyone ______.",["arrives","will arrive","arriving","arrived"],0,"after → hiện tại.","tc"],
 ["If the shipment ______ late again, we will change suppliers.",["is","will be","was","being"],0,"Điều kiện loại 1: if + hiện tại.","tc"],
 ["Before you ______ the office, please turn off the lights.",["leave","will leave","left","leaving"],0,"before → hiện tại.","tc"],
 ["As soon as the results ______ available, they will be posted online.",["are","will be","were","being"],0,"as soon as → hiện tại.","tc"],
 ["The conference room ______ right now, so we will meet in the lobby.",["is being cleaned","cleans","is cleaning","has cleaned"],0,"Phòng không tự dọn. Sau chỗ trống là “right now” (trạng từ), không có tân ngữ → bị động. Đang diễn ra → is being + V3: is being cleaned.","pv"],
 ["The documents ______ to you yesterday by express mail.",["were sent","sent","have sent","are sent"],0,"Tài liệu không tự gửi. Sau chỗ trống là “to you” (giới từ) và có “by express mail” → bị động. “yesterday” → quá khứ, chủ ngữ số nhiều → were sent.","pv"],
 ["Three new employees ______ since January.",["have been hired","hired","have hired","were hiring"],0,"Nhân viên được tuyển (không tự tuyển mình). Sau chỗ trống là “since January”, không có tân ngữ → bị động. since → hiện tại hoàn thành → have been hired.","pv"],
 ["The results of the survey ______ next Monday.",["will be announced","announce","will announce","have announced"],0,"Kết quả được công bố. Sau chỗ trống là “next Monday” (mốc thời gian, không phải tân ngữ) → bị động. Tương lai → will be announced.","pv"],
 ["By the time the inspector arrived, the problem ______.",["had already been fixed","has already fixed","was fixing","already fixed"],0,"Vấn đề được khắc phục (bị động, sau chỗ trống hết câu). Việc này xảy ra TRƯỚC “arrived” (quá khứ) → quá khứ hoàn thành bị động: had been fixed.","pv"],
 ["The bridge ______ when the storm hit the city.",["was being repaired","repaired","has been repaired","is repaired"],0,"Cây cầu được sửa (bị động, sau chỗ trống không có tân ngữ). Việc sửa ĐANG diễn ra thì bão ập đến (when + quá khứ) → quá khứ tiếp diễn bị động: was being repaired.","pv"],
 ["Since joining the company, Ms. Hanh ______ several awards for her designs.",["has won","wins","won","will win"],0,"Since + V-ing (từ khi…) → HTHT.","mix"],
 ["The company ______ record profits last year and expects even higher earnings this year.",["reported","reports","has reported","will report"],0,"last year → quá khứ đơn.","mix"],
 ["Ms. Vy ______ her position for only a month when she was promoted.",["had held","holds","has held","will hold"],0,"Trước 'was promoted' (QK) → QKHT.","mix"],
 ["By next March, the factory ______ fully operational for a decade.",["will have been","is","was","has been"],0,"By + tương lai → will have been.","mix"],
 ["The new branch ______ next Monday, according to the manager.",["will open","opened","has opened","had opened"],0,"next Monday → tương lai.","fs"],
 ["Over the last decade, the city ______ its public transportation network.",["has expanded","expands","is expanding","had expanded"],0,"Over the last decade → HTHT.","pp"],
 ["Ms. Trang ______ the company newsletter since she joined the team.",["has edited","edits","edited","is editing"],0,"since + mệnh đề QK → HTHT.","pp"],
 ["When I called the hotel, the receptionist told me that all rooms ______.",["had been booked","have been booked","are booked","will be booked"],0,"Tường thuật quá khứ, xảy ra trước → had been V3.","pap"]
];

const GRAM = [
{id:"wf",name:"Từ loại",
 rules:[["Trước danh từ → tính từ","a/the + ___ + N","a <em>detailed</em> report"],["Sau a/the/your/giới từ → danh từ","the/your/for + ___","your <em>registration</em>"],["Câu đủ S+V(+O) → trạng từ","has ___ V3 · V + O + ___","has <em>significantly</em> increased"],["Sau be/become/remain/seem → tính từ","be + ___","remains <em>affordable</em>"],["Danh từ ghép N + N","","<em>safety</em> regulations"]],
 sig:"Hậu tố: N = -tion, -ment, -ness, -ity, -ance · người = -er, -or, -ant, -ee · Adj = -ive, -ful, -able, -ous, -al · Adv = -ly.",
 trap:"-ly nhưng là tính từ: friendly, costly, timely, likely, orderly. Người vs vật: applicant/application, attendee/attendance.",
 qs:[
  ["The new software allows employees to complete reports more ______.",["efficiently","efficient","efficiency","efficiencies"],0,"Bổ nghĩa động từ complete → trạng từ."],
  ["Ms. Tran gave a ______ presentation on the quarterly budget.",["detailed","detail","detailing","detailedly"],0,"Giữa 'a' và danh từ → tính từ."],
  ["All ______ must submit their forms by Friday.",["applicants","apply","applications","applicable"],0,"Người nộp đơn → applicants."],
  ["Sales have increased ______ since the campaign began.",["steadily","steady","steadiness","steadied"],0,"Đủ S + V (nội động từ) → trạng từ."],
  ["The manager was ______ with the results of the survey.",["satisfied","satisfy","satisfying","satisfaction"],0,"Sau be; người cảm thấy → V3."],
  ["Please send your ______ for the conference by e-mail.",["registration","register","registered","registering"],0,"Sau tính từ sở hữu → danh từ."],
  ["The company's profits rose ______ in the third quarter.",["sharply","sharp","sharpness","sharpen"],0,"rose là nội động từ → trạng từ."],
  ["Mr. Vu is ______ for training new staff.",["responsible","responsibly","responsibility","responsibilities"],0,"be + adj; responsible for."],
  ["The hotel offers ______ rates for groups of ten or more.",["competitive","compete","competition","competitively"],0,"Trước danh từ → tính từ."],
  ["Please read the instructions ______ before using the machine.",["carefully","care","careful","caring"],0,"V + O + ___ → trạng từ."],
  ["The ______ of the new branch is scheduled for May.",["opening","open","opened","opens"],0,"Sau The, trước of → danh từ."],
  ["Online orders are ______ processed within 24 hours.",["typically","typical","typify","type"],0,"Giữa be và V3 → trạng từ."],
  ["The proposal was rejected because it was not financially ______.",["feasible","feasibly","feasibility","feasibleness"],0,"be + (adv) + adj."],
  ["Ms. Mai is known for her ______ to detail.",["attention","attend","attentive","attentively"],0,"Sau tính từ sở hữu → danh từ; cụm attention to detail."],
  ["The hotel is ______ located near the convention center.",["conveniently","convenient","convenience","conveniences"],0,"Giữa be và V3 → trạng từ."],
  ["Thank you for your ______ in this matter.",["cooperation","cooperate","cooperative","cooperatively"],0,"Sau your → danh từ."]
 ]},
{id:"pass",name:"Bị động",
 rules:[["be (chia thì) + V3","is/was/will be/has been + V3",""],["Không có tân ngữ sau chỗ trống → bị động","","The order <em>was shipped</em>."],["Có tân ngữ theo sau → chủ động","","Technicians <em>inspect</em> the machines."],["be + V3 + to V","be required / expected / scheduled / asked to",""],["Modal + be + V3","must / should / can be + V3",""]],
 sig:"Chủ ngữ là vật (report, order, product) → thường bị động.",
 trap:"Nội động từ không có bị động: occur, happen, arise, rise, arrive, remain, expire.",
 qs:[
  ["The annual report ______ to all shareholders next week.",["will be sent","will send","sends","sending"],0,"Chủ ngữ “The annual report” là vật, không tự gửi. Nhìn sau chỗ trống: “to all shareholders” bắt đầu bằng giới từ to → không có tân ngữ trực tiếp → bị động. “next week” → tương lai → will be sent."],
  ["Our technicians ______ all equipment before each shift.",["inspect","are inspected","inspection","to be inspected"],0,"Sau chỗ trống là “all equipment” (cụm danh từ, trả lời câu hỏi “kiểm tra CÁI GÌ?”) → có tân ngữ → chủ động. Chủ ngữ là người (technicians) tự kiểm tra → inspect."],
  ["Employees are ______ to wear ID badges at all times.",["required","require","requiring","requirement"],0,"Nhân viên BỊ yêu cầu (người khác yêu cầu họ). Sau chỗ trống là “to wear” (to V), không phải danh từ tân ngữ → bị động. Cấu trúc cố định: be required to + V."],
  ["The problem ______ because of a software error.",["occurred","was occurred","was occurring by","is occurred"],0,"occur (xảy ra) là nội động từ: “The problem occurred” đã đủ nghĩa, không cần tân ngữ và KHÔNG có dạng bị động → occurred. Loại ngay was occurred / is occurred."],
  ["The conference room has been ______ for the training.",["reserved","reserve","reserving","reservation"],0,"Phòng không tự đặt mà được đặt. Sau chỗ trống là “for the training” (giới từ for) → không có tân ngữ → has been + V3: reserved."],
  ["The new policy ______ to all staff last week.",["was announced","announced","announces","has announced"],0,"Chính sách không tự thông báo. Sau chỗ trống là “to all staff” (giới từ) → không có tân ngữ → bị động. “last week” → quá khứ, chủ ngữ số ít → was announced."],
  ["Visitors ______ to sign in at the front desk.",["are asked","ask","asking","have asked"],0,"Khách được (bị) yêu cầu ký tên. Sau chỗ trống là “to sign” (to V), không phải tân ngữ → bị động: be asked to V → are asked."],
  ["The renovation work is expected ______ by June.",["to be completed","to complete","completing","completed"],0,"Công việc cải tạo không tự hoàn thành mà được hoàn thành. Sau chỗ trống là “by June” (giới từ) → không có tân ngữ → bị động dạng to V: to be completed."],
  ["Construction costs ______ sharply this year.",["have risen","have been risen","were risen","are risen"],0,"rise (tăng) là nội động từ: không có tân ngữ và không có bị động → loại have been risen / were risen / are risen. “this year” (chưa kết thúc) → hiện tại hoàn thành: have risen."],
  ["All packages must ______ before 5 P.M.",["be shipped","ship","shipping","shipped"],0,"Kiện hàng không tự gửi. Sau chỗ trống là “before 5 P.M.” (giới từ) → không có tân ngữ → bị động. Sau must dùng be + V3 → be shipped."],
  ["The shipment ______ by a local courier tomorrow.",["will be delivered","delivers","will deliver","is delivering"],0,"Có “by a local courier” (by + người thực hiện) → dấu hiệu bị động rõ nhất. Lô hàng được giao; “tomorrow” → will be delivered."]
 ]},
{id:"sva",name:"Hòa hợp chủ – vị",
 rules:[["Bỏ qua cụm giới từ giữa S và V","","The list <s>of applicants</s> <em>is</em> …"],["each / every / either / neither + N → V số ít","",""],["A number of → V nhiều · The number of → V ít","",""],["Không đếm được → V số ít","","information, equipment, furniture, advice, luggage"],["Neither A nor B / Not only A but also B → chia theo B","",""]],
 sig:"Gạch bỏ cụm giới từ và mệnh đề quan hệ, tìm chủ ngữ thật rồi chia.",
 trap:"Each of the + N số nhiều vẫn chia số ít. furnitures, equipments là sai.",
 qs:[
  ["The list of approved vendors ______ updated every month.",["is","are","were","being"],0,"Chủ ngữ thật: The list."],
  ["A number of customers ______ complained about the delay.",["have","has","is","was"],0,"A number of → số nhiều."],
  ["Every employee ______ access to the new database.",["has","have","having","are having"],0,"Every + N → số ít."],
  ["All the office ______ will be replaced next week.",["furniture","furnitures","furnishing","furnish"],0,"furniture không đếm được."],
  ["Neither the manager nor the assistants ______ available on Monday.",["are","is","was","has been"],0,"Chia theo B (assistants)."],
  ["The information in these files ______ confidential.",["is","are","were","be"],0,"information không đếm được."],
  ["Each of the applicants ______ an interview next week.",["has","have","are having","were"],0,"Each of → số ít."],
  ["Not only the staff but also the manager ______ the training.",["attends","attend","are attending","have attended"],0,"Chia theo B (the manager)."],
  ["The number of visitors ______ increased this summer.",["has","have","are","were"],0,"The number of → số ít."],
  ["Most of the equipment in the lab ______ new.",["is","are","were","have been"],0,"Most of + N không đếm được → số ít."],
  ["One of our suppliers ______ raised its prices.",["has","have","are","were"],0,"One of + N số nhiều → chủ ngữ là One → số ít."]
 ]},
{id:"pron",name:"Đại từ",
 rules:[["Chủ ngữ / Tân ngữ","he → him · they → them · we → us",""],["Tính từ sở hữu + N","my · your · his · her · its · our · their",""],["Đại từ sở hữu (đứng một mình)","mine · yours · hers · ours · theirs",""],["Phản thân: trùng chủ ngữ / nhấn mạnh / by oneself","-self / -selves",""]],
 sig:"Có N ngay sau → tính từ sở hữu. Câu đủ, chỗ trống cuối câu → phản thân.",
 trap:"its (của nó) ≠ it's (it is).",
 qs:[
  ["Ms. Kim prefers to review the contracts ______ before signing them.",["herself","she","her","hers"],0,"Nhấn mạnh tự mình."],
  ["Please submit ______ expense reports to accounting.",["your","you","yours","yourself"],0,"Có N theo sau."],
  ["Mr. Park's proposal was accepted, but ______ was rejected.",["ours","our","us","ourselves"],0,"Đứng một mình làm chủ ngữ."],
  ["The director asked ______ to prepare the slides.",["us","we","our","ours"],0,"Sau động từ → tân ngữ."],
  ["Mr. Hoang designed the website by ______.",["himself","him","his","he"],0,"by oneself."],
  ["The company moved ______ headquarters to Ho Chi Minh City.",["its","it","it's","itself"],0,"Có N theo sau → its."],
  ["If you lose your badge, please inform ______ immediately.",["us","we","our","ours"],0,"Sau động từ → tân ngữ."],
  ["This laptop is mine, and that one is ______.",["hers","her","she","herself"],0,"Đứng một mình."],
  ["Employees should keep ______ desks clean.",["their","they","them","theirs"],0,"Có N theo sau."],
  ["The CEO ______ will greet the visitors at the entrance.",["himself","him","his","he's"],0,"Nhấn mạnh chủ ngữ."]
 ]},
{id:"prep",name:"Giới từ vs Liên từ",
 rules:[["Giới từ + N / V-ing","despite · because of · due to · during · instead of · prior to · following",""],["Liên từ + S + V","although · because · since · while · unless · once",""],["by = hạn chót · until = kéo dài đến","",""],["within = trong vòng · during = trong suốt · for + khoảng · since + mốc","",""],["at + giờ · on + ngày/thứ · in + tháng/năm","",""]],
 sig:"Sau chỗ trống có động từ chia → liên từ; chỉ có cụm danh từ → giới từ.",
 trap:"although/despite, because/because of, while/during: chọn theo cấu trúc trước, nghĩa sau.",
 qs:[
  ["______ the heavy rain, the event was held as planned.",["Despite","Although","Because","Even if"],0,"Theo sau là N → giới từ nhượng bộ."],
  ["The flight was delayed ______ the pilot was ill.",["because","because of","due to","owing to"],0,"Theo sau S + V → liên từ."],
  ["Please return the signed contract ______ Friday.",["by","until","in","at"],0,"Hạn chót → by."],
  ["Phones must be turned off ______ the performance.",["during","while","when","as"],0,"Theo sau N → during."],
  ["The store will remain open ______ 9 P.M.",["until","by","on","within"],0,"Kéo dài liên tục → until."],
  ["Refunds are available ______ 30 days of purchase.",["within","during","since","among"],0,"within + khoảng + of."],
  ["______ its small size, the device is very powerful.",["Despite","Although","Because of","Even though"],0,"N + nghĩa nhượng bộ."],
  ["Do not use your phone ______ you are driving.",["while","during","for","in"],0,"S + V → while."],
  ["The seminar will begin ______ 9:00 A.M.",["at","on","in","by"],0,"at + giờ."],
  ["We have worked with this supplier ______ more than ten years.",["for","since","during","at"],0,"for + khoảng."],
  ["______ the merger, the two companies will share one headquarters.",["Following","While","Although","Unless"],0,"following = sau (giới từ) + N."],
  ["Please contact Mr. Duc ______ any questions about the schedule.",["regarding","although","whereas","unless"],0,"regarding = về (giới từ) + N."],
  ["The pharmacy is located ______ the bank and the post office.",["between","among","along","across"],0,"between A and B."]
 ]},
{id:"rel",name:"Mệnh đề quan hệ",
 rules:[["who + V (người, chủ ngữ)","",""],["whom / which / that + S + V (tân ngữ)","",""],["whose + N (sở hữu)","",""],["where + S + V (nơi chốn)","",""],["Rút gọn: chủ động → V-ing · bị động → V3","","Employees <em>wishing</em> … · the report <em>submitted</em> …"]],
 sig:"Sau chỗ trống: N → whose · V → who/which · S + V → whom/which/where.",
 trap:"that không dùng sau dấu phẩy và sau giới từ.",
 qs:[
  ["Candidates ______ applications are incomplete will not be considered.",["whose","who","whom","which"],0,"Theo sau N → whose."],
  ["The printer, ______ was purchased last year, needs repairs.",["which","that","who","what"],0,"Sau dấu phẩy, vật → which."],
  ["Employees ______ to attend the workshop should register online.",["wishing","wish","wished","are wishing"],0,"Rút gọn chủ động."],
  ["The documents ______ by the legal team must be signed today.",["reviewed","review","reviewing","reviews"],0,"Rút gọn bị động."],
  ["Ms. Ha is the consultant ______ we hired.",["whom","whose","which","what"],0,"Người + S + V."],
  ["The man ______ is standing by the door is our new manager.",["who","whom","whose","which"],0,"Người + V."],
  ["This is the office ______ the interviews will take place.",["where","which","who","whose"],0,"Nơi chốn + mệnh đề đầy đủ."],
  ["Anyone ______ the event must register by Friday.",["attending","attend","attended","attends"],0,"Rút gọn chủ động."],
  ["The supplier from ______ we order paper has closed.",["whom","who","that","whose"],0,"Sau giới từ → whom (không dùng that, who)."],
  ["Ms. Lien, ______ team won the award, will speak at the banquet.",["whose","who","whom","which"],0,"Theo sau N (team) → whose."]
 ]},
{id:"ving",name:"To V / V-ing",
 rules:[["+ to V","plan · decide · agree · hope · expect · offer · refuse · fail · manage",""],["+ V-ing","avoid · consider · suggest · recommend · finish · enjoy · mind · postpone",""],["+ O + to V","allow · ask · encourage · require · remind · enable",""],["to là giới từ → V-ing","look forward to · be committed to · be used to · contribute to",""]],
 sig:"Sau mọi giới từ (for, by, before, after, without) → V-ing.",
 trap:"look forward to see là sai.",
 qs:[
  ["We look forward to ______ you at the meeting.",["seeing","see","seen","be seen"],0,"look forward to + V-ing."],
  ["The company plans ______ a new branch in Da Nang.",["to open","open","opening","opened"],0,"plan + to V."],
  ["Customers should avoid ______ the device near water.",["using","use","to use","used"],0,"avoid + V-ing."],
  ["The policy encourages employees ______ public transportation.",["to use","use","using","used"],0,"encourage + O + to V."],
  ["The firm is committed to ______ high-quality service.",["providing","provide","provided","provision"],0,"be committed to + V-ing."],
  ["The manager suggested ______ the meeting to Friday.",["moving","move","to move","moved"],0,"suggest + V-ing."],
  ["Mr. Thanh agreed ______ the contract next week.",["to sign","sign","signing","signed"],0,"agree + to V."],
  ["Thank you for ______ our survey.",["completing","complete","completed","to complete"],0,"Sau giới từ → V-ing."],
  ["The software enables users ______ files quickly.",["to share","share","sharing","shared"],0,"enable + O + to V."],
  ["Mr. Son is considering ______ his business to Hue.",["expanding","expand","to expand","expanded"],0,"consider + V-ing."],
  ["Visitors are not allowed ______ photographs in the gallery.",["to take","take","taking","taken"],0,"be allowed to V."]
 ]},
{id:"cond",name:"Câu điều kiện",
 rules:[["Loại 1: If + HTĐ, will / please + V","",""],["Loại 2: If + V2 (were), would + V","",""],["Loại 3: If + had V3, would have V3","",""],["Đảo ngữ","Should you … · Were I … · Had we …",""],["unless = if not · as long as / provided that = miễn là · in case = phòng khi","",""]],
 sig:"Đầu câu ___ + you + V nguyên mẫu, vế sau please → Should.",
 trap:"unless đã mang nghĩa phủ định.",
 qs:[
  ["If you ______ any questions, please contact us.",["have","will have","had had","having"],0,"Loại 1."],
  ["______ you need further assistance, please call our help desk.",["Should","Would","Had","Were"],0,"Đảo ngữ loại 1."],
  ["If the order had been placed earlier, it ______ on time.",["would have arrived","arrives","will arrive","would arrive"],0,"Loại 3."],
  ["The project will not be finished ______ more staff are hired.",["unless","if","although","because"],0,"Nếu không thuê → unless."],
  ["______ I known about the traffic, I would have left earlier.",["Had","If","Should","Were"],0,"Đảo ngữ loại 3."],
  ["You can return the item ______ you keep the receipt.",["as long as","unless","despite","even"],0,"Miễn là."],
  ["If the company ______ more funding, it would expand overseas.",["had","has","will have","having"],0,"Loại 2."],
  ["Bring an umbrella ______ it rains.",["in case","unless","although","so that"],0,"Phòng khi."],
  ["______ the weather be bad, the event will be moved indoors.",["Should","If","Unless","Were"],0,"Should + S + V (đảo ngữ loại 1)."],
  ["Unless you ______ by Friday, your reservation will be canceled.",["confirm","will confirm","confirmed","don't confirm"],0,"unless + hiện tại, không thêm not."]
 ]},
{id:"comp",name:"So sánh",
 rules:[["-er / more + than · nhấn mạnh: much, far, even, considerably","",""],["the -est / the most + in / of / ever","",""],["as + adj/adv + as (xét loại từ)","",""],["The + so sánh hơn, the + so sánh hơn","",""]],
 sig:"than → hơn · the … in/of → nhất · as … as → bằng.",
 trap:"very + so sánh hơn là sai.",
 qs:[
  ["This year's profits are ______ higher than last year's.",["much","very","more","most"],0,"Nhấn mạnh so sánh hơn."],
  ["Bao Minh is the ______ supplier in the region.",["largest","large","larger","most large"],0,"Nhất."],
  ["The new model runs as ______ as the old one.",["quietly","quiet","quieter","quietest"],0,"Bổ nghĩa runs → trạng từ."],
  ["The ______ you register, the cheaper the ticket.",["earlier","early","earliest","more early"],0,"The + so sánh hơn."],
  ["This printer is ______ reliable than the old one.",["more","much","most","very"],0,"more + adj dài + than."],
  ["Of all the candidates, Ms. Hien is the ______ qualified.",["most","more","much","many"],0,"Of all → nhất."],
  ["Our new office is twice as ______ as the old one.",["large","larger","largest","largely"],0,"as + adj + as."],
  ["Prices this year are ______ lower than expected.",["considerably","very","most","more"],0,"Nhấn mạnh so sánh hơn."],
  ["The new laptop is ______ lighter than the previous model.",["far","very","too","so"],0,"far + so sánh hơn."],
  ["This is the ______ efficient printer we have ever used.",["most","more","much","many"],0,"the most … ever."]
 ]},
{id:"conj",name:"Liên từ & từ nối",
 rules:[["both…and · either…or · neither…nor · not only…but also · whether…or","",""],["Từ nối sau dấu ; hoặc . và trước dấu phẩy","however · therefore · moreover · otherwise",""]],
 sig:"Thấy both / either / neither / not only → chọn từ đi cặp.",
 trap:"however không nối 2 mệnh đề bằng dấu phẩy.",
 qs:[
  ["Applicants must have both a degree ______ two years of experience.",["and","or","nor","but"],0,"both … and."],
  ["You can pay either online ______ at the front desk.",["or","and","nor","but"],0,"either … or."],
  ["The product is not only affordable ______ durable.",["but also","and also","or else","as well"],0,"not only … but also."],
  ["Sales were low in May; ______, they improved in June.",["however","although","despite","because"],0,"Tương phản, sau dấu ;."],
  ["The hotel is close to the beach; ______, it is popular with tourists.",["therefore","however","although","unless"],0,"Kết quả."],
  ["Neither the printer ______ the scanner is working.",["nor","or","and","but"],0,"neither … nor."],
  ["Please let us know ______ you will attend or not.",["whether","either","both","neither"],0,"whether … or not."],
  ["The design is simple ______ elegant.",["yet","either","neither","so that"],0,"yet = nhưng."],
  ["The price is reasonable; ______, the quality is excellent.",["moreover","however","otherwise","instead"],0,"Bổ sung ý → moreover."]
 ]},
{id:"part",name:"V-ing / V3 làm tính từ",
 rules:[["V-ing: chủ động / gây cảm xúc","","<em>rising</em> costs · <em>interesting</em> results"],["V3: bị động / người cảm thấy","","the <em>attached</em> file · <em>interested</em> customers"],["Cụm cố định","","attached · enclosed · revised · experienced · qualified · existing · leading · damaged"]],
 sig:"Danh từ tự làm → V-ing; bị làm → V3.",
 trap:"Vật gây cảm xúc → -ing; người cảm thấy → -ed.",
 qs:[
  ["Please review the ______ file before the meeting.",["attached","attach","attaching","attachment"],0,"File được đính kèm."],
  ["The results of the survey were very ______.",["encouraging","encourage","encouraged","encouragement"],0,"Kết quả gây khích lệ."],
  ["Only ______ candidates will be invited for an interview.",["qualified","qualify","qualifying","qualification"],0,"qualified candidates."],
  ["Due to ______ costs, the company raised its prices.",["rising","rise","risen","rose"],0,"Chi phí tự tăng."],
  ["We are pleased to announce the ______ date of the conference.",["revised","revise","revising","revision"],0,"Ngày được điều chỉnh."],
  ["The store will refund ______ items within 7 days.",["damaged","damage","damaging","damages"],0,"Hàng bị hỏng."],
  ["The CEO gave a very ______ speech.",["inspiring","inspire","inspired","inspiration"],0,"Gây cảm hứng."],
  ["______ customers will receive a 10% discount.",["Existing","Exist","Existed","Existence"],0,"existing customers."],
  ["The ______ staff handled the complaint professionally.",["experienced","experience","experiencing","experiences"],0,"experienced staff."],
  ["Please find the ______ brochure with this letter.",["enclosed","enclose","enclosing","enclosure"],0,"Được gửi kèm."]
 ]},
{id:"conf",name:"Cặp từ dễ nhầm",
 rules:[["rise (không tân ngữ) · raise + O","","Prices <em>rose</em>. · <em>raise</em> prices"],["lie – lay – lain (nằm) · lay – laid – laid + O (đặt)","",""],["affect (v) · effect (n)","",""],["borrow (mượn) · lend sb sth (cho mượn)","",""],["say sth · tell sb sth","",""],["a few + N đếm được · a little + không đếm được (few / little = rất ít)","",""],["most + N · almost all + N · most of the + N","",""],["another + N số ít · other + N số nhiều","",""]],
 sig:"Xét có tân ngữ không (rise/raise, lie/lay) và danh từ có đếm được không (few/little).",
 trap:"almost employees là sai → almost all employees / most employees.",
 qs:[
  ["The company plans to ______ prices next month.",["raise","rise","arise","rose"],0,"Có tân ngữ → raise."],
  ["______ employees work from home on Fridays.",["Most","Almost","Mostly","The most"],0,"most + N."],
  ["Could you ______ me your pen for a minute?",["lend","borrow","rent","owe"],0,"lend sb sth."],
  ["The new rules will ______ all departments.",["affect","effect","effective","affection"],0,"Cần động từ."],
  ["Please ______ the manager about the problem.",["tell","say","speak","talk"],0,"tell + người."],
  ["Only ______ seats are left, so book now.",["a few","few","a little","little"],0,"Đếm được; only a few."],
  ["Would you like ______ cup of coffee?",["another","other","others","the others"],0,"another + N số ít."],
  ["Ms. Linh ______ the documents on the desk this morning.",["laid","lay","lied","lain"],0,"Đặt + O, quá khứ."],
  ["The number of complaints has ______ sharply.",["risen","raised","arisen","rose"],0,"Không có tân ngữ → rise (has risen)."],
  ["There are ______ tickets left, so we may not get any.",["few","a few","little","a little"],0,"Gần như không còn → few."]
 ]}
];

/* Part 5 – từ vựng, cụm cố định (ETS style) */
const P5V = [
 ["Please ______ the attached form and return it by Friday.",["complete","attend","perform","apply"],0,"complete a form = điền đơn."],
 ["The new policy will take ______ on January 1.",["effect","place","part","care"],0,"take effect = có hiệu lực."],
 ["Employees are ______ to a 15-minute break every two hours.",["entitled","allowed","eligible","required"],0,"be entitled to + N = được hưởng."],
 ["Mr. Tan was ______ responsible for the success of the project.",["largely","widely","highly","deeply"],0,"largely responsible = phần lớn nhờ."],
 ["Our store offers a full ______ if you are not satisfied.",["refund","receipt","discount","payment"],0,"full refund = hoàn tiền toàn bộ."],
 ["Please ______ from using your phone during the performance.",["refrain","avoid","prevent","stop"],0,"refrain from + V-ing. avoid không đi với from."],
 ["Hotel guests have ______ to the fitness center at no extra charge.",["access","entrance","admission","approach"],0,"have access to = được sử dụng."],
 ["The keynote speech was ______ by more than 500 people.",["attended","participated","joined","gone"],0,"attend có thể bị động; participate cần 'in'."],
 ["Ms. Yen will be in ______ of the new project.",["charge","control","responsibility","management"],0,"in charge of = phụ trách."],
 ["Due to high ______, the concert has added a second performance.",["demand","request","supply","order"],0,"high demand = nhu cầu cao."],
 ["Please ______ your seat belt while the sign is on.",["fasten","attach","lock","tie"],0,"fasten a seat belt."],
 ["Applicants must have at least three years of ______ in sales.",["experience","practice","skill","career"],0,"experience in = kinh nghiệm."],
 ["Our technical support team is available around the ______.",["clock","time","day","hour"],0,"around the clock = 24/7."],
 ["The order will be shipped ______ receipt of payment.",["upon","within","during","among"],0,"upon receipt of = ngay khi nhận."],
 ["Please keep your receipt as ______ of purchase.",["proof","sign","mark","note"],0,"proof of purchase."],
 ["Mr. Hai will ______ the training session on Thursday.",["conduct","attend to","perform at","make"],0,"conduct a session/survey."],
 ["The museum is closed ______ renovations until May.",["for","at","by","to"],0,"closed for renovations."],
 ["We regret to ______ you that the event has been canceled.",["inform","explain","say","announce"],0,"inform sb that."],
 ["Please ______ to the manual for detailed instructions.",["refer","consult","look","check"],0,"refer to = tham khảo."],
 ["Ms. Phuong has been ______ to senior manager.",["promoted","advanced","raised","lifted"],0,"be promoted to."],
 ["All visitors must ______ with the safety regulations.",["comply","follow","obey","observe"],0,"comply with; các từ còn lại không đi với 'with'."],
 ["The contract is ______ for two years.",["valid","available","possible","capable"],0,"valid = có hiệu lực."],
 ["The flight was delayed because of ______ weather conditions.",["severe","strict","high","large"],0,"severe weather."],
 ["Please submit your expense report no ______ than Friday.",["later","after","more","longer"],0,"no later than = chậm nhất."],
 ["The company plans to ______ its operations into Southeast Asia.",["expand","extend","enlarge","increase"],0,"expand into."],
 ["Free parking is available to all ______ of the conference.",["participants","members","audiences","spectators"],0,"participants of a conference."],
 ["Ms. Linh made a ______ to the charity on behalf of the company.",["donation","donor","donate","donated"],0,"make a donation."],
 ["The meeting has been postponed until further ______.",["notice","news","notification","note"],0,"until further notice."],
 ["Please ______ a copy of your ID with the application.",["include","contain","consist","involve"],0,"include = gửi kèm."],
 ["The hotel can ______ groups of up to 200 people.",["accommodate","contain","admit","enter"],0,"accommodate = có sức chứa."],
 ["The marketing team will ______ a survey to gather feedback.",["conduct","take place","hold up","make up"],0,"conduct a survey."],
 ["Our sales ______ have increased by 15 percent.",["figures","numbers","counts","amounts"],0,"sales figures."],
 ["Customers can ______ their points for gift cards.",["redeem","reduce","refer","remain"],0,"redeem points = đổi điểm."],
 ["Due to a scheduling ______, the seminar will start at 10 A.M.",["conflict","fight","problem area","argument"],0,"scheduling conflict = trùng lịch."],
 ["The new branch will be ______ located near the subway station.",["conveniently","comfortably","closely","nearly"],0,"conveniently located."],
 ["Ms. Nga was ______ the Employee of the Year award.",["presented with","given to","provided","offered to"],0,"be presented with an award."],
 ["Please make sure the printer is turned off at the end of the ______.",["day","date","time","shift work"],0,"at the end of the day."],
 ["The CEO will ______ the opening speech at the conference.",["deliver","speak","say","tell"],0,"deliver a speech."],
 ["We are ______ to announce the opening of our new store.",["pleased","pleasing","pleasure","please"],0,"be pleased to announce."],
 ["Interested applicants should send a cover letter ______ with a résumé.",["along","together","also","plus"],0,"along with = cùng với."]
];

/* Part 5 nâng cao (700+) */
const P5A = [
 ["The board is expected to approve the merger, ______ some shareholders have raised concerns.",["although","despite","even","nevertheless"],0,"Theo sau S + V, nghĩa nhượng bộ → although. nevertheless là trạng từ, không nối mệnh đề."],
 ["Ms. Dao's proposal was chosen ______ its cost-effectiveness and innovative design.",["on account of","so that","whereas","in order that"],0,"on account of = because of + N."],
 ["______ to the newsletter must be submitted by May 3.",["Contributions","Contributors","Contributing","Contribute"],0,"Vật được nộp (must be submitted) → contributions (bài đóng góp)."],
 ["Only after the inspection was completed ______ to resume production.",["was the factory allowed","the factory was allowed","allowed the factory","the factory allowed"],0,"Only after … đầu câu → đảo trợ động từ lên trước chủ ngữ."],
 ["Not until the end of the quarter ______ the full impact of the new policy.",["will we know","we will know","we know","knowing"],0,"Not until … đầu câu → đảo ngữ."],
 ["The new regulations apply to all employees, ______ of their position.",["regardless","despite","notwithstanding","although"],0,"regardless of = bất kể."],
 ["Rarely ______ such a high level of customer satisfaction.",["has the company achieved","the company has achieved","achieved the company","the company achieving"],0,"Rarely đầu câu → đảo ngữ."],
 ["The software update is ______ to improve processing speed by 30 percent.",["projected","projecting","projection","project"],0,"be projected to V = được dự kiến."],
 ["Ms. Huong's ______ for the position is evident from her extensive experience.",["suitability","suitable","suitably","suit"],0,"Sau sở hữu cách → danh từ."],
 ["The director requested that every report ______ by Friday.",["be submitted","is submitted","was submitted","will be submitted"],0,"Câu giả định: request that + S + (be) V nguyên mẫu."],
 ["It is essential that the contract ______ before the end of the month.",["be signed","is signed","will be signed","signs"],0,"It is essential that + S + V nguyên mẫu."],
 ["Had the shipment arrived on time, we ______ the deadline.",["would have met","will meet","met","would meet"],0,"Đảo ngữ loại 3 → would have V3."],
 ["The committee will select the proposal ______ best meets the criteria.",["that","what","whose","whom"],0,"Vật + V → that/which."],
 ["______ the new manager's leadership, the department has become more productive.",["Under","Over","Within","Among"],0,"under sb's leadership."],
 ["The company's ______ growth has attracted many investors.",["sustained","sustaining","sustain","sustainably"],0,"sustained growth = tăng trưởng bền vững (được duy trì)."],
 ["Mr. Long has been ______ in negotiating the new supply agreement.",["instrumental","instrument","instrumentally","instrumentation"],0,"be instrumental in = đóng vai trò then chốt."],
 ["Customers should read the terms carefully, ______ some services incur additional fees.",["as","so","unless","despite"],0,"as = because."],
 ["Please note that the price ______ excludes delivery charges.",["quoted","quoting","quote","quotation"],0,"Rút gọn bị động: the price (which was) quoted."],
 ["______ the director nor her assistants were aware of the error.",["Neither","Either","Both","Not only"],0,"Neither … nor."],
 ["The new branch will be staffed ______ by local employees.",["predominantly","predominant","predominance","predominate"],0,"Bổ nghĩa cho V3 → trạng từ."],
 ["Personal use of company vehicles is strictly ______.",["prohibited","prohibiting","prohibition","prohibitive"],0,"is strictly prohibited."],
 ["The renovation, ______ was originally scheduled for June, has been postponed.",["which","that","what","it"],0,"Sau dấu phẩy → which."],
 ["Ms. Nhung will attend the conference ______ Mr. Quang, who is on leave.",["in place of","according to","as well","instead"],0,"in place of + N = thay cho."],
 ["______ completing the training, new employees will receive a certificate.",["Upon","Since","Once that","While being"],0,"Upon + V-ing = ngay khi."],
 ["The proposal is ______ to be approved, given the strong support from the board.",["likely","probably","possibly","perhaps"],0,"be likely to V."],
 ["The CEO's speech was so ______ that many employees volunteered for the initiative.",["compelling","compelled","compel","compulsion"],0,"so + adj + that; bài phát biểu thuyết phục → compelling."],
 ["The company has ______ its commitment to reducing carbon emissions.",["reaffirmed","reassured","recovered","resigned"],0,"reaffirm a commitment = tái khẳng định."],
 ["Any changes to the itinerary must be approved ______ advance.",["in","by","on","at"],0,"in advance."],
 ["The report highlights the need for ______ communication between departments.",["closer","closely","closest","close to"],0,"Trước danh từ → tính từ (so sánh hơn)."],
 ["______ of the two proposals was considered feasible within the budget.",["Neither","None","Nor","Not"],0,"Neither of the two + V số ít."],
 ["The firm's revenue grew by 12 percent, ______ analysts' expectations.",["exceeding","exceeded","exceeds","to exceed"],0,"Mệnh đề rút gọn chỉ kết quả → V-ing."],
 ["The technician will arrive at 2 P.M. ______ there are no further delays.",["provided that","in spite of","so as","whereas"],0,"provided that = miễn là."],
 ["The marketing budget has been ______ allocated to digital advertising.",["disproportionately","disproportionate","disproportion","disproportions"],0,"Giữa has been và V3 → trạng từ."],
 ["Mr. Bui is ______ the most experienced engineer on the team.",["arguably","argue","argument","arguable"],0,"arguably + so sánh nhất = có thể nói là."],
 ["The seminar is open to all staff, ______ registration is required in advance.",["although","so","therefore","because of"],0,"Nối 2 mệnh đề, nghĩa tương phản."]
];
