/* Từ vựng [từ, IPA (Mỹ), loại, nghĩa, ghi chú] + phát âm */

const V = {
"Văn phòng":[["deadline","ˈdedlaɪn","n","hạn chót","meet a deadline"],["submit","səbˈmɪt","v","nộp","submission (n)"],["supervisor","ˈsuːpərvaɪzər","n","người giám sát","supervise (v)"],["colleague","ˈkɑːliːɡ","n","đồng nghiệp",""],["assign","əˈsaɪn","v","giao việc","assignment · g câm"],["memo","ˈmemoʊ","n","thông báo nội bộ",""],["reimburse","ˌriːɪmˈbɜːrs","v","hoàn trả chi phí","reimbursement"],["supplies","səˈplaɪz","n","đồ dùng","office supplies"],["photocopier","ˈfoʊtoʊkɑːpiər","n","máy photo",""],["headquarters","ˈhedkwɔːrtərz","n","trụ sở chính",""],["extension","ɪkˈstenʃn","n","số máy lẻ; sự gia hạn","extend (v)"],["confidential","ˌkɑːnfɪˈdenʃl","adj","bảo mật",""]],
"Nhân sự":[["applicant","ˈæplɪkənt","n","ứng viên","apply · application"],["candidate","ˈkændɪdət","n","ứng viên",""],["qualified","ˈkwɑːlɪfaɪd","adj","đủ năng lực","qualification"],["résumé","ˈrezəmeɪ","n","sơ yếu lý lịch",""],["recruit","rɪˈkruːt","v","tuyển dụng","recruitment"],["promote","prəˈmoʊt","v","thăng chức; quảng bá","promotion"],["retire","rɪˈtaɪər","v","nghỉ hưu","retirement"],["resign","rɪˈzaɪn","v","từ chức","resignation · g câm"],["benefits","ˈbenɪfɪts","n","phúc lợi","benefits package"],["orientation","ˌɔːriənˈteɪʃn","n","buổi định hướng",""],["personnel","ˌpɜːrsəˈnel","n","nhân sự","nhấn âm cuối"],["evaluation","ɪˌvæljuˈeɪʃn","n","sự đánh giá","evaluate"]],
"Tài chính":[["budget","ˈbʌdʒɪt","n","ngân sách","within budget"],["revenue","ˈrevənuː","n","doanh thu",""],["expense","ɪkˈspens","n","chi phí","expensive"],["invoice","ˈɪnvɔɪs","n","hóa đơn",""],["receipt","rɪˈsiːt","n","biên lai","p câm"],["account","əˈkaʊnt","n","tài khoản","accountant · accounting"],["audit","ˈɔːdɪt","n","kiểm toán","auditor"],["profit","ˈprɑːfɪt","n","lợi nhuận","profitable"],["quarter","ˈkwɔːrtər","n","quý","quarterly"],["estimate","ˈestɪmət","n","bản ước tính","v: ˈestɪmeɪt"],["payment","ˈpeɪmənt","n","khoản thanh toán",""],["deposit","dɪˈpɑːzɪt","n","tiền đặt cọc",""]],
"Ngân hàng":[["withdraw","wɪðˈdrɔː","v","rút tiền","withdrawal"],["transaction","trænˈzækʃn","n","giao dịch",""],["balance","ˈbæləns","n","số dư","account balance"],["loan","loʊn","n","khoản vay","apply for a loan"],["interest rate","ˈɪntrəst reɪt","n","lãi suất",""],["statement","ˈsteɪtmənt","n","bản sao kê","bank statement"],["installment","ɪnˈstɔːlmənt","n","khoản trả góp","pay in installments"],["overdue","ˌoʊvərˈduː","adj","quá hạn","overdue payment"],["tax","tæks","n","thuế",""],["fee","fiː","n","phí","late fee"],["currency","ˈkɜːrənsi","n","tiền tệ",""],["teller","ˈtelər","n","giao dịch viên ngân hàng",""]],
"Kinh doanh":[["merger","ˈmɜːrdʒər","n","sáp nhập","merge"],["launch","lɔːntʃ","v","ra mắt",""],["campaign","kæmˈpeɪn","n","chiến dịch","g câm"],["competitor","kəmˈpetɪtər","n","đối thủ","compete · competitive"],["client","ˈklaɪənt","n","khách hàng",""],["contract","ˈkɑːntrækt","n","hợp đồng",""],["negotiate","nɪˈɡoʊʃieɪt","v","đàm phán","negotiation"],["proposal","prəˈpoʊzl","n","đề xuất","propose"],["survey","ˈsɜːrveɪ","n","khảo sát",""],["expand","ɪkˈspænd","v","mở rộng","expansion"],["strategy","ˈstrætədʒi","n","chiến lược","strategic"],["branch","bræntʃ","n","chi nhánh",""]],
"Marketing":[["advertise","ˈædvərtaɪz","v","quảng cáo","advertisement"],["brand","brænd","n","thương hiệu",""],["target","ˈtɑːrɡɪt","n/v","mục tiêu; nhắm tới","target customers"],["consumer","kənˈsuːmər","n","người tiêu dùng",""],["promotion","prəˈmoʊʃn","n","khuyến mãi; thăng chức",""],["feedback","ˈfiːdbæk","n","phản hồi","không đếm được"],["market share","ˈmɑːrkɪt ʃer","n","thị phần",""],["endorse","ɪnˈdɔːrs","v","ủng hộ, chứng thực","endorsement"],["slogan","ˈsloʊɡən","n","khẩu hiệu",""],["sponsor","ˈspɑːnsər","n/v","nhà tài trợ; tài trợ",""],["publicity","pʌbˈlɪsəti","n","sự quảng bá",""],["launch event","lɔːntʃ ɪˈvent","n","sự kiện ra mắt",""]],
"Mua bán":[["merchandise","ˈmɜːrtʃəndaɪs","n","hàng hóa","không đếm được"],["discount","ˈdɪskaʊnt","n","giảm giá",""],["refund","ˈriːfʌnd","n","hoàn tiền","full refund"],["warranty","ˈwɔːrənti","n","bảo hành","under warranty"],["purchase","ˈpɜːrtʃəs","v/n","mua","đọc 'pơ-chợs'"],["order","ˈɔːrdər","n","đơn hàng","place an order"],["out of stock","ˌaʊt əv ˈstɑːk","adj","hết hàng",""],["retail","ˈriːteɪl","n","bán lẻ","retailer"],["voucher","ˈvaʊtʃər","n","phiếu",""],["exchange","ɪksˈtʃeɪndʒ","v","đổi hàng",""],["item","ˈaɪtəm","n","món hàng",""],["checkout","ˈtʃekaʊt","n","quầy tính tiền",""]],
"Sản xuất & kho":[["manufacture","ˌmænjuˈfæktʃər","v","sản xuất","manufacturer"],["factory","ˈfæktəri","n","nhà máy",""],["inventory","ˈɪnvəntɔːri","n","hàng tồn kho",""],["warehouse","ˈwerhaʊs","n","nhà kho",""],["shipment","ˈʃɪpmənt","n","lô hàng","ship"],["deliver","dɪˈlɪvər","v","giao hàng","delivery"],["supplier","səˈplaɪər","n","nhà cung cấp","supply"],["equipment","ɪˈkwɪpmənt","n","thiết bị","không đếm được"],["assemble","əˈsembl","v","lắp ráp","assembly line"],["inspect","ɪnˈspekt","v","kiểm tra","inspection"],["defective","dɪˈfektɪv","adj","bị lỗi","defect"],["package","ˈpækɪdʒ","n","gói hàng",""]],
"Du lịch":[["itinerary","aɪˈtɪnəreri","n","lịch trình",""],["reservation","ˌrezərˈveɪʃn","n","sự đặt chỗ","reserve"],["boarding pass","ˈbɔːrdɪŋ pæs","n","thẻ lên máy bay",""],["depart","dɪˈpɑːrt","v","khởi hành","departure"],["destination","ˌdestɪˈneɪʃn","n","điểm đến",""],["luggage","ˈlʌɡɪdʒ","n","hành lý","không đếm được"],["fare","fer","n","giá vé xe/tàu","đồng âm fair"],["round-trip","ˌraʊnd ˈtrɪp","adj","khứ hồi",""],["delay","dɪˈleɪ","n/v","sự trì hoãn",""],["accommodation","əˌkɑːməˈdeɪʃn","n","chỗ ở",""],["aisle","aɪl","n","lối đi","s câm"],["souvenir","ˌsuːvəˈnɪr","n","quà lưu niệm",""]],
"Giao thông":[["commute","kəˈmjuːt","v","đi làm hằng ngày","commuter"],["traffic jam","ˈtræfɪk dʒæm","n","tắc đường",""],["pedestrian","pəˈdestriən","n","người đi bộ",""],["intersection","ˌɪntərˈsekʃn","n","ngã tư",""],["detour","ˈdiːtʊr","n","đường vòng",""],["vehicle","ˈviːəkl","n","phương tiện","h câm"],["fuel","ˈfjuːəl","n","nhiên liệu",""],["toll","toʊl","n","phí cầu đường",""],["platform","ˈplætfɔːrm","n","sân ga",""],["transfer","trænsˈfɜːr","v","chuyển tuyến","n: ˈtrænsfɜːr"],["route","ruːt","n","tuyến đường",""],["parking lot","ˈpɑːrkɪŋ lɑːt","n","bãi đỗ xe",""]],
"Sự kiện":[["agenda","əˈdʒendə","n","chương trình họp",""],["venue","ˈvenjuː","n","địa điểm",""],["attendee","əˌtenˈdiː","n","người tham dự","attend · attendance"],["register","ˈredʒɪstər","v","đăng ký","register for"],["postpone","poʊstˈpoʊn","v","hoãn","postpone + V-ing"],["reschedule","ˌriːˈskedʒuːl","v","đổi lịch",""],["keynote","ˈkiːnoʊt","n","bài phát biểu chính",""],["refreshments","rɪˈfreʃmənts","n","đồ ăn nhẹ",""],["banquet","ˈbæŋkwɪt","n","tiệc lớn",""],["seminar","ˈsemɪnɑːr","n","hội thảo",""],["host","hoʊst","v","tổ chức",""],["award","əˈwɔːrd","n","giải thưởng",""]],
"Nhà hàng & khách sạn":[["cuisine","kwɪˈziːn","n","ẩm thực",""],["catering","ˈkeɪtərɪŋ","n","dịch vụ đồ ăn","cater"],["chef","ʃef","n","đầu bếp","ch đọc /ʃ/"],["appetizer","ˈæpɪtaɪzər","n","món khai vị",""],["vacancy","ˈveɪkənsi","n","phòng trống; vị trí trống",""],["amenities","əˈmenətiz","n","tiện nghi",""],["complimentary","ˌkɑːmplɪˈmentri","adj","miễn phí (tặng)",""],["housekeeping","ˈhaʊskiːpɪŋ","n","bộ phận buồng phòng",""],["bill","bɪl","n","hóa đơn",""],["beverage","ˈbevərɪdʒ","n","đồ uống",""],["dine","daɪn","v","ăn tối","dining room"],["patron","ˈpeɪtrən","n","khách quen",""]],
"Bất động sản":[["renovate","ˈrenəveɪt","v","cải tạo","renovation"],["construction","kənˈstrʌkʃn","n","xây dựng","construct"],["property","ˈprɑːpərti","n","bất động sản",""],["tenant","ˈtenənt","n","người thuê",""],["landlord","ˈlændlɔːrd","n","chủ nhà",""],["lease","liːs","n","hợp đồng thuê",""],["facility","fəˈsɪləti","n","cơ sở vật chất",""],["contractor","ˈkɑːntræktər","n","nhà thầu",""],["utilities","juːˈtɪlətiz","n","điện, nước, ga",""],["spacious","ˈspeɪʃəs","adj","rộng rãi",""],["residential","ˌrezɪˈdenʃl","adj","thuộc khu dân cư",""],["vacant","ˈveɪkənt","adj","trống",""]],
"Hợp đồng & pháp lý":[["agreement","əˈɡriːmənt","n","thỏa thuận",""],["terms","tɜːrmz","n","điều khoản","terms and conditions"],["clause","klɔːz","n","điều khoản (một mục)",""],["signature","ˈsɪɡnətʃər","n","chữ ký",""],["comply","kəmˈplaɪ","v","tuân thủ","comply with"],["regulation","ˌreɡjuˈleɪʃn","n","quy định",""],["violate","ˈvaɪəleɪt","v","vi phạm",""],["expire","ɪkˈspaɪər","v","hết hạn","expiration"],["renew","rɪˈnuː","v","gia hạn","renewal"],["obligation","ˌɑːblɪˈɡeɪʃn","n","nghĩa vụ",""],["liable","ˈlaɪəbl","adj","chịu trách nhiệm pháp lý","be liable for"],["authorize","ˈɔːθəraɪz","v","ủy quyền, cho phép","authorization"]],
"Sức khỏe & công nghệ":[["appointment","əˈpɔɪntmənt","n","lịch hẹn",""],["prescription","prɪˈskrɪpʃn","n","đơn thuốc","prescribe"],["pharmacy","ˈfɑːrməsi","n","nhà thuốc","ph đọc /f/"],["insurance","ɪnˈʃʊrəns","n","bảo hiểm",""],["install","ɪnˈstɔːl","v","cài đặt","installation"],["device","dɪˈvaɪs","n","thiết bị",""],["malfunction","ˌmælˈfʌŋkʃn","n","trục trặc",""],["technician","tekˈnɪʃn","n","kỹ thuật viên",""],["upgrade","ˌʌpˈɡreɪd","v","nâng cấp",""],["access","ˈækses","n/v","truy cập","have access to"],["database","ˈdeɪtəbeɪs","n","cơ sở dữ liệu",""],["password","ˈpæswɜːrd","n","mật khẩu","w câm"]],
"Môi trường & cộng đồng":[["recycle","ˌriːˈsaɪkl","v","tái chế",""],["renewable","rɪˈnuːəbl","adj","tái tạo được","renewable energy"],["emission","iˈmɪʃn","n","khí thải",""],["volunteer","ˌvɑːlənˈtɪr","n","tình nguyện viên","nhấn âm cuối"],["donate","ˈdoʊneɪt","v","quyên góp","donation"],["charity","ˈtʃærəti","n","tổ chức từ thiện",""],["resident","ˈrezɪdənt","n","cư dân",""],["fundraiser","ˈfʌndreɪzər","n","sự kiện gây quỹ",""],["conservation","ˌkɑːnsərˈveɪʃn","n","bảo tồn",""],["sustainable","səˈsteɪnəbl","adj","bền vững",""],["waste","weɪst","n","rác thải",""],["community","kəˈmjuːnəti","n","cộng đồng",""]],
"Động từ Part 1":[["stack","stæk","v","xếp chồng",""],["lean","liːn","v","dựa","lean against"],["arrange","əˈreɪndʒ","v","sắp xếp",""],["hang","hæŋ","v","treo",""],["board","bɔːrd","v","lên xe/tàu",""],["examine","ɪɡˈzæmɪn","v","xem xét kỹ",""],["sweep","swiːp","v","quét",""],["unload","ʌnˈloʊd","v","dỡ hàng",""],["pour","pɔːr","v","rót",""],["fold","foʊld","v","gấp",""],["mow","moʊ","v","cắt cỏ","mow the lawn"],["browse","braʊz","v","xem lướt",""]],
"Động từ Part 5":[["accommodate","əˈkɑːmədeɪt","v","đáp ứng; có sức chứa",""],["implement","ˈɪmplɪment","v","triển khai","implementation"],["acquire","əˈkwaɪər","v","mua lại; đạt được","acquisition"],["allocate","ˈæləkeɪt","v","phân bổ",""],["anticipate","ænˈtɪsɪpeɪt","v","dự đoán",""],["enhance","ɪnˈhæns","v","nâng cao",""],["facilitate","fəˈsɪlɪteɪt","v","tạo điều kiện",""],["oversee","ˌoʊvərˈsiː","v","giám sát",""],["verify","ˈverɪfaɪ","v","xác minh",""],["streamline","ˈstriːmlaɪn","v","tinh giản",""],["consolidate","kənˈsɑːlɪdeɪt","v","hợp nhất",""],["accompany","əˈkʌmpəni","v","đi kèm",""]],
"Danh từ Part 5":[["expertise","ˌekspɜːrˈtiːz","n","chuyên môn",""],["initiative","ɪˈnɪʃətɪv","n","sáng kiến",""],["compliance","kəmˈplaɪəns","n","sự tuân thủ",""],["consensus","kənˈsensəs","n","sự đồng thuận",""],["priority","praɪˈɔːrəti","n","ưu tiên",""],["capacity","kəˈpæsəti","n","sức chứa; công suất",""],["procedure","prəˈsiːdʒər","n","thủ tục",""],["component","kəmˈpoʊnənt","n","bộ phận, linh kiện",""],["incentive","ɪnˈsentɪv","n","khoản khuyến khích",""],["feasibility","ˌfiːzəˈbɪləti","n","tính khả thi",""],["reputation","ˌrepjuˈteɪʃn","n","danh tiếng",""],["objective","əbˈdʒektɪv","n","mục tiêu",""]],
"Tính từ Part 5":[["available","əˈveɪləbl","adj","có sẵn; rảnh",""],["eligible","ˈelɪdʒəbl","adj","đủ điều kiện","eligible for"],["affordable","əˈfɔːrdəbl","adj","giá phải chăng",""],["reliable","rɪˈlaɪəbl","adj","đáng tin cậy","rely on"],["efficient","ɪˈfɪʃnt","adj","hiệu quả","efficiency"],["mandatory","ˈmændətɔːri","adj","bắt buộc",""],["temporary","ˈtempəreri","adj","tạm thời",""],["upcoming","ˈʌpkʌmɪŋ","adj","sắp tới",""],["previous","ˈpriːviəs","adj","trước đó",""],["accurate","ˈækjərət","adj","chính xác","accuracy"],["comprehensive","ˌkɑːmprɪˈhensɪv","adj","toàn diện",""],["outstanding","aʊtˈstændɪŋ","adj","nổi bật; chưa thanh toán","outstanding balance"]],
"Trạng từ Part 5":[["approximately","əˈprɑːksɪmətli","adv","xấp xỉ",""],["immediately","ɪˈmiːdiətli","adv","ngay lập tức",""],["promptly","ˈprɑːmptli","adv","đúng giờ, nhanh",""],["recently","ˈriːsntli","adv","gần đây","đi với HTHT"],["currently","ˈkɜːrəntli","adv","hiện tại",""],["temporarily","ˌtempəˈrerəli","adv","tạm thời",""],["significantly","sɪɡˈnɪfɪkəntli","adv","đáng kể",""],["frequently","ˈfriːkwəntli","adv","thường xuyên",""],["previously","ˈpriːviəsli","adv","trước đây",""],["regularly","ˈreɡjələrli","adv","đều đặn",""],["nearly","ˈnɪrli","adv","gần như",""],["shortly","ˈʃɔːrtli","adv","sắp, chẳng bao lâu","shortly after"]],
"Cụm từ cố định":[["in charge of","ɪn ˈtʃɑːrdʒ əv","phr","phụ trách",""],["on behalf of","ɑːn bɪˈhæf əv","phr","thay mặt",""],["in advance","ɪn ədˈvæns","phr","trước (thời gian)",""],["as of","æz əv","phr","kể từ (ngày)","as of May 1"],["in accordance with","ɪn əˈkɔːrdns wɪð","phr","theo đúng",""],["at no extra charge","æt noʊ ˈekstrə tʃɑːrdʒ","phr","không tính thêm phí",""],["until further notice","ənˈtɪl ˈfɜːrðər ˈnoʊtɪs","phr","cho đến khi có thông báo mới",""],["out of order","aʊt əv ˈɔːrdər","phr","bị hỏng",""],["up to date","ˌʌp tə ˈdeɪt","phr","cập nhật",""],["on short notice","ɑːn ʃɔːrt ˈnoʊtɪs","phr","báo gấp",""],["take into account","teɪk ˈɪntuː əˈkaʊnt","phr","cân nhắc",""],["keep track of","kiːp træk əv","phr","theo dõi",""]]
};

const SOUNDS = [
 {t:"th vô thanh",ipa:"/θ/",how:"Đầu lưỡi đặt nhẹ giữa hai hàm răng, thổi hơi, cổ không rung. Người Việt hay đọc thành 'th' tiếng Việt hoặc /s/.",w:["think","three","thank","month","method","third","thousand"],p:[["think","sink"],["three","tree"],["mouth","mouse"]]},
 {t:"th hữu thanh",ipa:"/ð/",how:"Giống /θ/ nhưng rung cổ họng.",w:["this","that","the","other","weather","together","although"],p:[["they","day"],["then","ten"]]},
 {t:"sh",ipa:"/ʃ/",how:"Chu môi ra trước, lưỡi lùi lại. Khác /s/ (môi dẹt, lưỡi sát răng).",w:["ship","shipment","sure","session","machine","special","insurance"],p:[["ship","sip"],["shoe","sue"],["shell","sell"]]},
 {t:"i dài – i ngắn",ipa:"/iː/ – /ɪ/",how:"/iː/: kéo mép như cười, đọc dài. /ɪ/: thả lỏng, ngắn, gần 'i' và 'ê'.",w:["seat","sit","leave","live","feel","fill","team"],p:[["seat","sit"],["leave","live"],["heat","hit"],["cheap","chip"]]},
 {t:"a bẹt – e",ipa:"/æ/ – /e/",how:"/æ/: mở miệng rộng, lai giữa 'a' và 'e'. /e/: mở vừa như 'e' tiếng Việt.",w:["bad","man","plan","staff","bed","men","sell"],p:[["bad","bed"],["man","men"],["had","head"],["sad","said"]]},
 {t:"ơ cong lưỡi",ipa:"/ɜːr/",how:"Môi tròn nhẹ, cong lưỡi lên, 'ơ' kéo dài kèm /r/.",w:["work","first","service","purchase","third","early","return"],p:[["work","walk"],["word","ward"],["bird","bored"]]},
 {t:"ă ngắn",ipa:"/ʌ/",how:"Miệng mở vừa, ngắn và dứt khoát như 'ă'. Khác /æ/ (mở rộng hơn).",w:["budget","lunch","public","customer","bus","cup","company"],p:[["cup","cap"],["cut","cat"],["lunch","launch"]]},
 {t:"u dài – u ngắn",ipa:"/uː/ – /ʊ/",how:"/uː/: chu môi tròn, dài. /ʊ/: môi lỏng, ngắn.",w:["pool","food","move","full","book","look","good"],p:[["pool","pull"],["fool","full"]]},
 {t:"âm cuối /l/",ipa:"/l/",how:"Cuối từ, đầu lưỡi chạm lợi trên và giữ. Người Việt hay bỏ, nghe thành 'fai', 'cô'.",w:["call","file","school","deal","sell","mail","detail"],p:[["file","fight"],["cold","code"]]},
 {t:"âm cuối /s/ /z/ /t/ /d/",ipa:"-s · -t · -d",how:"Phải bật rõ phụ âm cuối: nghe sót âm cuối là sai số ít/nhiều và thì quá khứ.",w:["reports","needs","booked","planned","asked","clothes","months"],p:[["save","safe"],["live","life"],["coat","code"]]},
 {t:"ch – j",ipa:"/tʃ/ – /dʒ/",how:"/tʃ/: bật hơi, chu môi. /dʒ/: giống nhưng rung cổ.",w:["check","change","charge","purchase","job","manager","schedule"],p:[["cheap","jeep"],["chain","Jane"]]},
 {t:"số teen / ty",ipa:"-ˈtiːn / -ti",how:"-teen nhấn âm cuối, kéo dài. -ty nhấn âm đầu, -ty đọc nhẹ, giọng Mỹ gần 'đi'.",w:["thirteen","thirty","fourteen","forty","fifteen","fifty","eighteen","eighty"],p:[["thirteen","thirty"],["fifteen","fifty"],["nineteen","ninety"]]}
];
const PAIRS = [["ship","sheep"],["live","leave"],["sit","seat"],["bad","bed"],["man","men"],["think","sink"],["three","tree"],["walk","work"],["fifteen","fifty"],["thirteen","thirty"],["fourteen","forty"],["sixteen","sixty"],["cost","coast"],["law","low"],["rice","rise"],["price","prize"],["light","right"],["play","pray"],["file","fire"],["glass","grass"],["hit","heat"],["full","fool"],["cheap","chip"],["mouse","mouth"],["sue","shoe"],["said","sad"],["fan","van"],["bag","back"],["pen","pan"],["hard","heard"],["ten","then"],["day","they"],["sell","shell"],["cut","cat"],["cap","cup"],["coat","code"],["leave","leaf"],["fair","fear"],["ward","word"],["boss","bus"],["lunch","launch"],["live","life"],["save","safe"],["bear","beer"],["wash","watch"]];
const ED = [["wanted","ɪd","t"],["booked","t","k"],["planned","d","n"],["needed","ɪd","d"],["finished","t","ʃ"],["called","d","l"],["delayed","d","eɪ"],["shipped","t","p"],["reported","ɪd","t"],["increased","t","s"],["printed","ɪd","t"],["changed","d","dʒ"],["watched","t","tʃ"],["decided","ɪd","d"],["arrived","d","v"],["faxed","t","s"],["invited","ɪd","t"],["received","d","v"],["worked","t","k"],["organized","d","z"],["laughed","t","f"],["attended","ɪd","d"],["stopped","t","p"],["opened","d","n"],["helped","t","p"],["visited","ɪd","t"],["played","d","eɪ"],["asked","t","k"],["started","ɪd","t"],["used","d","z"],["checked","t","k"],["added","ɪd","d"],["moved","d","v"],["pushed","t","ʃ"],["ended","ɪd","d"],["explained","d","n"],["fixed","t","s"],["completed","ɪd","t"],["showed","d","oʊ"],["dropped","t","p"]];
const SE = [["offices","ɪz","s"],["jobs","z","b"],["products","s","t"],["changes","ɪz","dʒ"],["meetings","z","ŋ"],["reports","s","t"],["boxes","ɪz","s"],["files","z","l"],["clients","s","t"],["prices","ɪz","s"],["plans","z","n"],["desks","s","k"],["packages","ɪz","dʒ"],["calls","z","l"],["chefs","s","f"],["months","s","θ"],["buses","ɪz","s"],["days","z","eɪ"],["watches","ɪz","tʃ"],["shops","s","p"],["cups","s","p"],["cars","z","r"],["classes","ɪz","s"],["books","s","k"],["dishes","ɪz","ʃ"],["pens","z","n"],["maps","s","p"],["bridges","ɪz","dʒ"],["photos","z","oʊ"],["nights","s","t"],["roles","z","l"],["branches","ɪz","tʃ"],["sizes","ɪz","z"],["graphs","s","f"],["benefits","s","t"]];
const STRESS = [["de-vel-op-ment",1],["em-ploy-ee",2],["pho-tog-ra-pher",1],["pho-to-graph",0],["ec-o-nom-ic",2],["e-con-o-my",1],["in-for-ma-tion",2],["re-ceive",1],["of-fice",0],["com-pa-ny",0],["op-por-tu-ni-ty",2],["fi-nan-cial",1],["en-gi-neer",2],["man-u-fac-tur-er",2],["sched-ule",0],["de-liv-er-y",1],["a-vail-a-ble",1],["ap-point-ment",1],["cus-tom-er",0],["re-spon-si-ble",1],["pres-en-ta-tion",2],["ac-count-ant",1],["sup-pli-er",1],["ex-pe-ri-ence",1],["in-ter-na-tion-al",2],["as-sist-ant",1],["man-ag-er",0],["ex-ec-u-tive",1],["per-son-nel",2],["ca-reer",1],["a-gen-da",1],["ho-tel",1],["de-lay",1],["pur-chase",0],["con-trib-ute",1],["in-dus-try",0],["ca-pac-i-ty",1],["ad-di-tion-al",1],["cer-tif-i-cate",1],["com-mit-tee",1],["con-trac-tor",0],["de-part-ment",1],["e-quip-ment",1],["in-ven-to-ry",0],["main-te-nance",0],["pho-to-cop-i-er",0],["re-cep-tion-ist",1],["ref-er-ence",0],["re-im-burse-ment",2],["sat-is-fac-tion",2],["ap-pli-ca-tion",2],["par-tic-i-pate",1],["ad-min-is-tra-tive",1],["ap-pro-pri-ate",1],["ben-e-fit",0],["cal-en-dar",0],["con-fer-ence",0],["de-ter-mine",1],["ec-o-nom-i-cal",2],["ex-hi-bi-tion",2],["vol-un-teer",2],["guar-an-tee",2]];
const LINKS = [
 {t:"Phụ âm cuối + nguyên âm đầu → nối liền",ex:["check it out","pick it up","fill out the form","turn off","an hour","look at it"]},
 {t:"t giữa hai nguyên âm → đọc nhẹ như 'đ' (giọng Mỹ)",ex:["better","water","meeting","get it","a lot of","what about"]},
 {t:"d / t + you → 'dʒ' / 'tʃ'",ex:["did you","would you","could you","meet you","don't you","last year"]},
 {t:"Âm bị nuốt giữa hai phụ âm",ex:["next week","last month","don't know","must be","just finished","handbag"]},
 {t:"Dạng đọc yếu của từ chức năng",ex:["a cup of coffee","for a while","bread and butter","I can go","to the office","from Monday"]},
 {t:"Rút gọn trong hội thoại",ex:["I'm going to call","I want to leave","I've got to go","Let me see","Do you want to come","What are you doing"]}
];
